apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stress1-ng-deployment
    instana-autotrace: "true"
  name: stress1-ng-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress1-ng-webserver
  template:
    metadata:
      labels:
        app: stress1-ng-webserver
    spec:
      containers:
      - args:
        - -c
        - "100"
        - -l
        - "100"
        - -v
        command:
        - /stress-ng
        image: alexeiled/stress-ng
        name: stress1-ng
        resources:
          limits:
            cpu: 150m
            memory: 150Mi
          requests:
            cpu: 100m
            memory: 100Mi
